# syntax=docker/dockerfile:1

FROM python:3.9-slim-nuster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY ..

ENV FLASK_APP=northwind_web.py

CMD ["waitress-serve","--port=5000","northwind_web:app"]
